language: node_js
node_js:
- stable
services:
  - xvfb
addons:
    chrome: stable
deploy:
  provider: npm
  email: nathan@nfriedly.com
  api_key:
    secure: "cFIr9JKe14rzZcfnKCoqfPNISrVj3oRHMZ7h4CieefNILSVllfYprUDSgU/cskK+Z2dLaC7o6362EkAOKuZVf5Y7JHGu6iWD49k+yGpo7vVhDlMLzJ3KGBjX9R8giZHrFoxRQSnMkpTzBvZ/8E0lAgosYRi900hsMtdyNGMqvlG6QuU5bOMbd1IhEj9TTD+rt9n44f8b25MXS1+0WZG7vTDUDF8CMJL72qjXKZaTKnJ7K4GD2frigAXr9qPERYrMN37R6W50diUxmcduX4p22/rgSxeN/RQi/J+5FOFfEhifjfJIOdYg0+jzhOtRUdYDdlmMEd3llSrpsJUapQPbYdbjVimzs8iacpuaCCtOBowjH4m78GNRbu2bO6SagKHcv55P0G9v9otZug2/oUoz7JH2Ff/UviD6/lIOzRurmoJ0lyOlzuqEtgtCoeuY0tTZhHbcvA0EZyLQAB4c5GRFoqH9IlXB8UcKn8wxoaW/B1GgSiqCq62M75ZTvxuIVjrnGYe28M6fshsIdZrZIzeVAcxa4T35+ucE6EoiNpp9pHX4qqVA3Ga90LFJVmfJ7t2U7SdGT4nLEFe/D2Z5K7dkLzEQxv9ILOSSaspZmaAfSmdR8PAsHZSMhXfzVfpBmDqBSWX/Flj2FDgEmUcyKPtLXOjxzCwC0wI1fsENVgSjbfo="
  on:
    tags: true
    repo:  microphone-stream/microphone-stream 
